# Generated by Django 4.2.3 on 2023-07-28 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_author_alter_post_category'),
        ('gallery', '0002_mediaitem_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/')),
                ('image_title', models.BooleanField(default=False, verbose_name='Является обложкой?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
    ]
