# Generated by Django 4.2.3 on 2023-07-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_media_items_post_media_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_items',
        ),
    ]
